### ISSUE TITLE
No tasks shown in ClusterODM's web interface

### ISSUE THREAD

**Issue by stephenwinn16** [OpenDroneMap/ClusterODM#118]
### What is the problem?

I have connected 5 NodeODM instances to a ClusterODM instance and can run a split-merge workflow using these resources. When I check the ClusterODM admin web interface (on port 10000), I can see each of the nodes, their status and the number of queued tasks. However, when I check the task web interface (on port 6001, changed from the default 3000), **none of the tasks appear**. See screenshots below: 

<img width="1390" alt="admin_web" src="https://github.com/user-attachments/assets/74441db0-8365-45ad-9fd9-3ad59ed2c529">

<img width="1153" alt="admin_tasklist" src="https://github.com/user-attachments/assets/99f992e8-1e35-43ef-b6ba-2ca9f3bed080">

### What should be the expected behavior?

I would expect each of the running tasks and their progress to be show on the task web interface. 

### How can we reproduce this? 

Here is the script I am using to start the NodeODM and ClusterODM instances on my university HPC cluster (PS: if this script is of interest to supplement the documentation in the [ClusterODM, NodeODM, SLURM, with Singularity on HPC](https://github.com/OpenDroneMap/docs/pull/198) section, let me know. Thanks @sbonaime for your tutorial, it was a great place to start).  

```shell
#!/bin/sh
#SBATCH --job-name=ClusterODM
#SBATCH --partition=compute
#SBATCH --time=23:59:00
#SBATCH --nodes=5
#SBATCH --mem=256G
#SBATCH --exclusive
#SBATCH --output=job_%j.out
#SBATCH --error=job_%j.err

# Load required modules
module load singularity

echo "========================= Initialisation ==========================="
WD=/path/to/wrk/dir1
cd $WD
case=case_name

# --- CLUSTERODM 
rm -rf ClusterODM_$case
git clone https://github.com/OpenDroneMap/ClusterODM ClusterODM_$case
cd ClusterODM_$case
singularity pull --force --disable-cache docker://opendronemap/clusterodm:latest
singularity exec --bind $PWD:/var/www clusterodm_latest.sif bash ../install_img.sh
cd $WD

# --- NODEODM
rm -rf NodeODM_$case
git clone https://github.com/OpenDroneMap/NodeODM NodeODM_$case
cd NodeODM_$case
singularity pull --force --disable-cache docker://opendronemap/nodeodm:latest
singularity exec --bind $PWD:/var/www nodeodm_latest.sif bash ../install_img.sh
cd $WD

echo 'Done with initialisation' 

# Get list of hostnames and write to file 
srun hostname > hostfile_$SLURM_JOB_ID.txt
sleep 5

echo "========================= Launching NodeODMs ==========================="
# Launch NodeODM on N nodes 
cd $WD/NodeODM_$case

while read p;  do 
	echo 'Starting nodeODM on node' $p; srun --nodes=1 singularity run --bind $PWD:/var/www nodeodm_latest.sif --port 3000 &
done <  ../hostfile_$SLURM_JOB_ID.txt

sleep 15 # give the nodes a chance to start  

echo "========================= Launching ClusterODM ==========================="

# Launch clusterODM on the "master" node 
cd $WD/ClusterODM_$case

CLI_PORT=6000
CODM_PORT=6001
singularity run --bind $PWD:/var/www clusterodm_latest.sif --admin-cli-port $CLI_PORT --port $CODM_PORT & 
sleep 20 # give ClusterODM a chance to start

# Add the nodes to the ClusterODM
ClusterODMaddr=$SLURMD_NODENAME
echo "ClusterODM node is $ClusterODMaddr"

while read p; do 
	echo "Adding $p to ClusterODM list ..."
	echo "NODE ADD $p 3000" | ncat $ClusterODMaddr $CLI_PORT #send the NODE ADD message with ncat
	sleep 5
done <  ../hostfile_$SLURM_JOB_ID.txt

# 
sleep 10 
echo "========================= Launching the job ==========================="

# Params
res=10
fq=high
pcq=medium
minnf=20000

wrk=/path/to/wrk/dir2
cd $wrk 

images_dir=$wrk/src/$case/code/images/
output_dir=$wrk/src/$case

# Pull ODM 
sing_path=sifs/odm_$case.sif

singularity pull --disable-cache $sing_path docker://opendronemap/odm:latest 

singularity -v run \
		--bind $images_dir:$output_dir/code/images \
		--writable-tmpfs \
		$sing_path \
		--project-path $output_dir \
		--orthophoto-resolution $res \
		--auto-boundary \
		--optimize-disk-space \
		--pc-quality $pcq \
		--skip-3dmodel \
		--min-num-features $minnf \
		--no-gpu \
		--radiometric-calibration camera+sun \
		--feature-quality $fq \
		--sm-cluster "http://$ClusterODMaddr:$CODM_PORT/" \
		--split 1500 \
		--split-overlap 200 \
		--rerun-all

# Clean up
rm $sing_path
```

**Comment by sbonaime** [comment]
- You can remove from your sbatch script the installation part which needs to be done once and also the "singularity pull " or maybe you can do an installation script.
- To see your job in the web interface, you need to start it from the web interface. Can you try removing the "Launching the job " of your script and use the localhost:6001 interface to load your images and start the job ?

**Comment by stephenwinn16** [comment]
Thanks @sbonaime for your quick response. 

> You can remove from your sbatch script the installation part which needs to be done once and also the "singularity pull " or maybe you can do an installation script.

I had grouped all the steps in this one script for completeness - I understand this "Initialisation" step only needs to be done once. 

> To see your job in the web interface, you need to start it from the web interface. 

Ah, I see. I do not wish to have to connect to the web interface to upload the images and launch the job (the images are already available on the remote cluster storage), I was interested in being able to follow task progress through the web interface in case any nodes/steps posed a problem. Thanks for the explanation though.

**Comment by sbonaime** [comment]
Maybe you can check each individual node with web interface doing ssh port forwarding. 
Lets say your first node name is node_1. 

From you host node you can do 
``` 
ssh -L 3000:node_1:9001  you_user_name@node_1
```
Then on your host node you can go to localhost:9001 and you will see port 3000 of node_1. I think you will be able to see the job status. But I am not sure ! 
If it is workin, you need to open for each node a ssh connection and change the local port 9002,9003,...

**Comment by sbonaime** [comment]
Can you show us what is install_img.sh ? Maybe we can add it to this repo.

**Comment by stephenwinn16** [comment]
>Maybe you can check each individual node with web interface doing ssh port forwarding.

Thanks for the suggestion. If I check the NodeODM web interface on a node-by-node basis, I can indeed see the status of tasks so if I spot any issues I will just port-forward to the relevant node and check tasks there. 

> Can you show us what is install_img.sh ? Maybe we can add it to this repo.

Sure, the `install_img.sh` simply contains the lines to run the npm install command: 

```
cd /var/www
npm install --production 
exit
```
