### ISSUE TITLE
Does it work with NodeMicMac ? 

### ISSUE THREAD

**Issue by kikislater** [OpenDroneMap/ClusterODM#15]
Didn't check the code but simple question : 
Could it work with NodeMicMac or need rework ?

**Comment by smathermather** [comment]
It would definitely need rework.

**Comment by kikislater** [comment]
Ok thank you !

**Comment by pierotofy** [comment]
Actually, you can use ClusterODM just fine with NodeMICMAC.

**Comment by kikislater** [comment]
Waohhhh !!! I will try this week many thnaks

**Comment by smathermather** [comment]
ClusterODM works with NodeMICMAC, but I would assume that split-merge does not... . Is this correct @pierotofy, and was this what you were interested in @kikislater?

**Comment by pierotofy** [comment]
Obviously no split-merge in MicMac, correct.

**Comment by kikislater** [comment]
Hum hum, there is another approach for MicMac no problem

**Comment by kikislater** [comment]
pymicmac here does it : https://github.com/ImproPhoto/pymicmac
I will try to work on it !
