### ISSUE TITLE
Add AWS autoscaling driver

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ClusterODM#20]
Amazon AWS is a popular cloud provider.

**Comment by garysieling** [comment]
This would be an interesting project - do you have any guidance on where to start (e.g. documentation for an interface to implement)

**Comment by pierotofy** [comment]
Hey @garysieling :hand: thanks for the interest!

Pretty much you would need to make a copy of https://github.com/OpenDroneMap/ClusterODM/blob/master/libs/asr-providers/digitalocean.js and modify it to work with AWS, so expose the relevant options of docker-machine specific to AWS and remove those specific to Digital Ocean as indicated on https://docs.docker.com/machine/drivers/aws/

**Comment by pierotofy** [comment]
I suggest passing the `--log-level debug` option while testing to see how the docker-machine command is being invoked.
