### ISSUE TITLE
Task table entry sometimes appears to be missing when using ASR

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ClusterODM#26]
WebODM clients will sometimes report the error message "Invalid route for taskId xxxx-xxxx-xxx-xxxx:info, no task table entry." after a task is completed.

**Comment by pierotofy** [comment]
This should have been fixed in more recent versions.

**Comment by gjsa73** [comment]
Using WebODM v1.4.0 and have just experienced this issue after submitting a large number of jobs to Lightning nodes.

The jobs completed processing (logging into my Lightning account confirmed this), but after approx two days, WebODM showed the jobs in various states of progress and the log updates had stalled.  After restarting WebODMand the other docker containers, this error message replaced the stalled progress bars:

![image](https://user-images.githubusercontent.com/21994806/84606744-f5a4fe80-aeeb-11ea-914d-2eb642765561.png)

**Comment by protoblade** [comment]
I dont think it is as it does this with the most recent version using aws ASR - opendronemap/clusterodm      latest    40f13171fcef
