### ISSUE TITLE
Why switch nodes many times in working?

### ISSUE THREAD

**Issue by yingyi-ma** [OpenDroneMap/ClusterODM#31]
122 photos
Options: split: 50, split-overlap: 50
Why switch nodes many times in working???

![image](https://user-images.githubusercontent.com/49050636/62176187-1ff0da80-b373-11e9-9c08-11949bb59f72.png)

description：
122 pictures are ortho-spliced according to 50 segmentation. There are four nodes. When splicing, they are not allocated to three nodes for splicing, but to 1-2-3 for splicing, then 1-2-4 for splicing and then 1-4 for processing. I want to ask why the nodes are changed in this way instead of fixed for three nodes for processing.

like this
1.
![image](https://user-images.githubusercontent.com/49050636/62111197-a7dad400-b2e2-11e9-83a7-d8d5afec42fe.png)
2.
![image](https://user-images.githubusercontent.com/49050636/62111212-af01e200-b2e2-11e9-9d0a-71d1fe7b30aa.png)
3.
![image](https://user-images.githubusercontent.com/49050636/62111223-b628f000-b2e2-11e9-9f3b-6d73456d5f32.png)
4.
![image](https://user-images.githubusercontent.com/49050636/62111238-bcb76780-b2e2-11e9-86b8-8b90330e66f6.png)

**Comment by pierotofy** [comment]
Hey @yingyi-ma could you please elaborate further?

**Comment by yingyi-ma** [comment]
> Hey @yingyi-ma could you please elaborate further?

ok. update my issue and upload a Flow chart pic. 
 
description：122 pictures are ortho-spliced according to 50 segmentation. There are four nodes. When splicing, they are not allocated to three nodes for splicing, but to 1-2-3 for splicing, then 1-2-4 for splicing and then 1-4 for processing. I want to ask why the nodes are changed in this way instead of fixed for three nodes for processing. 

thanks.

**Comment by pierotofy** [comment]
So the algorithm "rotates" the nodes and pick ones that have not been used in a while (if all other factors are equal). This is to minimize the chance that a node might receive two tasks simultaneously (if they are uploaded at the same time), without using locks.

If this is not a desired behavior, you can always comment out https://github.com/OpenDroneMap/ClusterODM/blob/master/libs/nodes.js#L183 and keep `bestNode.turn` to zero.
