### ISSUE TITLE
Setting up ClusterODM setup using WebODM

### ISSUE THREAD

**Issue by neelduttahere** [OpenDroneMap/ClusterODM#51]
Hey Everyone,
I am struggling to make ClusterODM work with web odm. I have setup 3 nodes running **NodeODM**. And setup **ClusterODM** in a server spec machine (no apparent reason why i choose a server machine for this task). As the guide says, i connect all the node to ClusterODM using telnet, and I can see the nodes are online. Now how do I implement this cluster setup from WebODM? As per the documentation in [https://docs.opendronemap.org/large.html#distributed-split-merge](url), in CLI odm, you need to add **--sm-cluster http://cluster_odm_ip:3001**.

My question again, is how do I trigger this action in webODM? In the custom settings option in webODM, there is a field to enter the URL of clusterODM, but I havent had any luck with that. What I need to know, is at what process stage, does odm create sub-models and distribute them to different nodes to process?

**Setup :**
**WebODM** (SYSTEM (1))-->**ClusterODM**(SYSTEM (3))+--------**NodeODM**
                                                                                               +--------**NodeODM**
                                                                                               +--------**NodeODM** 

**System specifications:**
Following are the system specifications.

**Machine running WebODM: (1)**
CPU: Ryzen 7 3600
RAM: 16gb DDR4 2133
500GB SSD and 1TB HDD

**node machine specs: (2)**
CPU: Ryzen 7 3600
RAM: 16gb DDR4 2133
500GB SSD and 1TB HDD

**System running ClusterODM: (A server Machine) (3)**
CPU: Intel Xeon Silver 4208 2.10 Ghz
RAM: 32GB
HDD: 198GB

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:

**Comment by neelduttahere** [comment]
> Could we move this conversation over to the forum at https://community.opendronemap.org? 🙏 The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! 👍

cool
