### ISSUE TITLE
The version information in package.json is different from the version information in /info.

### ISSUE THREAD

**Issue by chisquare88** [OpenDroneMap/ClusterODM#56]
The version information in package.json is different from the version information in /info.

https://github.com/OpenDroneMap/ClusterODM/blob/420895b1522c69a895db205cf6e606a22f62fcb4/libs/proxy.js#L139

https://github.com/OpenDroneMap/ClusterODM/blob/420895b1522c69a895db205cf6e606a22f62fcb4/package.json#L3

**Comment by pierotofy** [comment]
The first value is the NodeODM API version ClusterODM is able to speak. The second is ClusterODM's version.
