### ISSUE TITLE
aws s3 bucker creation+autoscaling

### ISSUE THREAD

**Issue by hrshovon** [OpenDroneMap/ClusterODM#59]
Hello,
I have been testing cluster odm on local machines+some aws instances. Since clusterodm supports autoscaling/creating and destroying nodes on demand, I would like to know a bit more about the process of setting it up. The description provided in https://github.com/OpenDroneMap/ClusterODM/blob/master/docs/aws.md is not very clear for aws newbie like me.
So from here what I understand is:
1. Given that I have aws account, I need to create an s3 bucket with unblocked access.
2. Then I guess I need to deploy clusterodm in an instance in aws?
3. Also, I did not quite understand what this means. 

> Select an AMI (machine image) to run - Ubuntu has a handy AMI finder.

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
