### ISSUE TITLE
add suggested version of node?

### ISSUE THREAD

**Issue by danbjoseph** [OpenDroneMap/ClusterODM#75]
what version of node is suggested? 
would it make sense to add a [`.nvmrc` file](https://github.com/nvm-sh/nvm#nvmrc)?

**Comment by pierotofy** [comment]
I'm currently running on `v15.10.0` on my dev machine. But I think any recent version will work just fine.

I wasn't aware of .nvmrc, but if it's helpful to you, sure! Open a PR?
