### ISSUE TITLE
Fix - AWS Autoscaling w/ Docker-Machine

### ISSUE THREAD

**Issue by Karl-Keller** [OpenDroneMap/ClusterODM#85]
**Problem**

Docker-Machine fails to create node instances with an AWS asr request in some configurations of the AWS platform.  Specifically, it fails for those configurations without a default VPC or subnet and/or those that use region zones, e.g. us-east-1c, for the VPC/subnet/security group resources.  Yielding the errors below - 

No default vpc/subnet -

**_(debug-machine) Couldn't determine your account Default VPC ID : "default-vpc is 'none'"
Error setting machine configuration from flags provided: amazonec2 driver requires either the --amazonec2-subnet-id or --amazonec2-vpc-id option or an AWS Account with a default vpc-id_**

No availability Zone -

**_Error creating machine: Error in driver during machine creation: Error launching instance: InvalidParameterValue: Value (us-east-1a) for parameter availabilityZone is invalid. Subnet 'subnet-****' is in the availability zone us-east-1c
	status code: 400,_**

Defining a default VPC or subnet requires interaction with AWS support.  Defining the zone is straightforward given the parameter in the JSON.

**Expectation**

What is expected is that when running cluster-odm locally via 'node index.js --asr aws.json' assuming a properly formed aws.json file, the docker-machine invocation should create a new machine, load docker, and invoke a containerized node.

**Reproduction**

In order to reproduce this error, in an AWS environment with the configuration above, launch local ClusterODM with the --asr aws.json config flag reflecting that environment.  Telnet to 8080 and run 'asr viewcmd <# images>'. This provides the docker-machine command reflecting the information provided in the asr config.  Copy that docker-machine command and attempt to execute it in the command line.  If a VPC and subnet are not defaulted in the AWS environment, the machine will not be created.  If the AWS resources are contained in zone of a region, e.g. a,b,c, the machine will not be created.

The command line for Docker-Machine described above provides a more descriptive error than simply using the WebODM interface to launch a processing job.  That approach simply fails with the error below;

node index.js --asr aws.json
info: ClusterODM 1.5.3 started with PID 14656
info: Starting admin CLI on 8080
warn: No admin CLI password specified, make sure port 8080 is secured
info: Starting admin web interface on 10000
warn: No admin password specified, make sure port 10000 is secured
info: Cloud: LocalCloudProvider
info: ASR: AWSAsrProvider
info: Can write to S3
info: Found docker-machine executable
info: Loaded 1 nodes
info: Loaded 0 routes
info: Starting http proxy on 3000
**_info: Trying to create machine... (1)
warn: Cannot create machine: Error: docker-machine exited with code 1
info: Trying to create machine... (2)
warn: Cannot create machine: Error: docker-machine exited with code 1_**

**Resolution**

The problem resolution is limited in scope to the definition of the AWSAsrProvider extension of the AbstractASRProvider class in ./ClusterODM/libs/asr-providers/aws.js.  Documentation must be updated in ~/ClusterODM/docs/aws.md.

The following provides the reference variable names in Docker-Machine required to translate between the JSON naming and the Docker-Machine naming for the variable names.  https://gdevillele.github.io/machine/drivers/aws/

**Comment by Karl-Keller** [comment]
Current status:  updates to aws.js and aws.md in my branch to support fix.  Currently testing.  Successfully generates a new machine within the AWS EC2 infrastructure.  Fails predictably at the docker install afterwards (part of 19.03.9.sh) and gracefully terminates the node.

**Comment by Karl-Keller** [comment]
![image](https://user-images.githubusercontent.com/32310135/144507288-f15ce246-7e40-4a50-891d-d7dfca4680ff.png)
In testing, the first automatically launched and added node for my AWS environment.

**Comment by daniel-eidi** [comment]
could your share how you did it? I am having the same erros that you reported. Do I have to change this files ( aws.js and aws.md)? Thank you.

**Comment by pierotofy** [comment]
This should be fixed with #87
