### ISSUE TITLE
Add Azure support for auto-scaling

### ISSUE THREAD

**Issue by theoway** [OpenDroneMap/ClusterODM#90]
### What is the problem?

No option to integrate Azure components for storage & compute.

### What should be the expected behavior?

One should be able to use **Blob Storage/File Share** for storing the results and add configuration file to auto-scale by spinning up new Azure Container Instances or removing them.

### How can we reproduce this? (What steps did you do to trigger the problem? If applicable, please include multiple screenshots of the problem! Be detailed)

It's a feature enhancement request.

**Comment by theoway** [comment]
I am quite well-versed with Azure components and experienced with Azure Blob Storage and have also used NodeODM with Azure Container Instances. I'd LOVE to add Azure support!!! It'd be great if someone could point out where should I start looking. Or anything that can be helpful.

**Comment by pierotofy** [comment]
For blob storage, one would have to expand/modify support for uploading file results just like we do for S3: https://github.com/OpenDroneMap/NodeODM/blob/b076c6f1b72854fdb22c40e8be1611312f96e0ab/libs/Task.js#L514

For container instances, adding a new azure ASR provider with docker-machine would probably work (see examples of other providers here: https://github.com/OpenDroneMap/ClusterODM/tree/master/libs/asr-providers)

**Comment by theoway** [comment]
@pierotofy Thanks for the heads-up! Will get on it and make a PR soon!

**Comment by kendrickcc** [comment]
Not sure if relevant but MS does have blobfuse available now to allow access to blob storage from a VM. https://github.com/Azure/azure-storage-fuse 

I am able to mount a container to my VM for ODM. An example is in GitHub under kendrickcc/odm-azure-wf2

**Comment by pierotofy** [comment]
Closing for now; PRs to add support for Azure still most welcome :pray:
