### ISSUE TITLE
No Splitting of Jobs

### ISSUE THREAD

**Issue by cooljackgi** [OpenDroneMap/ClusterODM#96]
There is no spliting of projects in my cluster.
these are my options: 
Optionen: auto-boundary: true, fast-orthophoto: true, split: 40, split-overlap: 15, rerun-from: dataset

#	Node	Status	Queue	Engine	API	CPU Cores	RAM available	Flags	-
1	20.113.*.*3:3000	Online	0/1	odm 2.8.1	2.2.0	4	97.38%		
2	20.54.*.*0:3000	Online	1/1	odm 2.8.1	2.2.0	4	51.87%		
3	20.113.*.*3:3000	Online	0/1	odm 2.8.1	2.2.0	4	97.93%		

only one node is used any idea how to change this behaver?
I have a Photo set of 760 pics.

**Comment by cooljackgi** [comment]
Do the nodes have to be in the same network?

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
